apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.database.user | b64enc | quote }}
  password: {{ required "A database password is required" .Values.database.password | b64enc | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.database.user .Values.database.password .Release.Name .Values.database.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  jwt-secret: {{ required "A JWT secret is required" .Values.jwtSecret | b64enc | quote }}