apiVersion: v1
kind: Secret
metadata:
  name: terrafusionpro-db-credentials
  labels:
    app: terrafusionpro
    part-of: terrafusionpro
type: Opaque
stringData:
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  user-service-url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/user_service"
  property-service-url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/property_service"
  form-service-url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/form_service"
  report-service-url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/report_service"
  analysis-service-url: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/analysis_service"
---
apiVersion: v1
kind: Secret
metadata:
  name: terrafusionpro-jwt
  labels:
    app: terrafusionpro
    part-of: terrafusionpro
type: Opaque
stringData:
  secret: "${JWT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  name: terrafusionpro-replit-auth
  labels:
    app: terrafusionpro
    part-of: terrafusionpro
type: Opaque
stringData:
  client-id: "${REPLIT_CLIENT_ID}"
  client-secret: "${REPLIT_CLIENT_SECRET}"