apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-service
  namespace: terrafusionpro
  labels:
    app: analysis-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-service
  template:
    metadata:
      labels:
        app: analysis-service
    spec:
      containers:
      - name: analysis-service
        image: terrafusionpro/analysis-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "5003"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: terrafusionpro-secrets
              key: database-url
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: terrafusionpro
spec:
  selector:
    app: analysis-service
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP