apiVersion: v1
kind: Secret
metadata:
  name: terrafusionpro-secrets
  namespace: terrafusionpro
type: Opaque
data:
  # These values should be base64 encoded and not committed to source control
  # In a real environment, use a secrets management solution like Vault, Sealed Secrets, or cloud provider secrets
  # The values below are placeholders and should be replaced with real values in the actual deployment
  database-url: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlLnRlcnJhZnVzaW9ucHJvOjU0MzIvdGVycmFmdXNpb25wcm8= # postgres://username:password@postgres-service.terrafusionpro:5432/terrafusionpro
  jwt-secret: dGVycmFmdXNpb25wcm8tc2VjcmV0LWtleS0xMjM0NTY3ODkw # terrafusionpro-secret-key-1234567890