apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: terrafusionpro
  labels:
    app: web-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: terrafusionpro/web-client:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "http://api-gateway"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: terrafusionpro
spec:
  selector:
    app: web-client
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP